
name: main- curl

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: trigger wkflw
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/nalin745/test-heml/dispatches --data '{"event_type": "build_application"}'
          

      - name: Build with Maven
        run: |
          echo "Hi testing buddy" 
          echo "check oone"
        
