
name: main- curl ow

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Triger test helm repo workflow
      uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: nalin745
          repo: test-helm
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: gradle.yml
          ref: main
    - name: Build with Maven
      run: |
        echo "Hi testing buddy" 
        echo "check one"
        
