
name: main- curl ow

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: ${{ secrets.PAT_USERNAME}}
          repo: test-helm
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: gradle.yml
        
    - name: Build with Maven
      run: |
        echo "Hi testing buddy" 
        echo "check one"
        
